name: build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'build version number'
        default: "latest"
        required: true
env:
  conan-version: 1.60.0
jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        shell: pwsh
        run: |
          $Version = '${{ github.event.inputs.version }}'
          if ($Version -eq 'latest') {
            $Version = (Get-Date -Format "yyyy.MM.dd") + ".0"
          }
          echo "version=$Version" >> $Env:GITHUB_OUTPUT

  build-native:
    name: Native build
    runs-on: ${{ matrix.runner }}
    needs: [preflight]
    env:
      CONAN_LOGIN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_READ_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: [ win, osx, linux ]
        arch: [ x64, arm64 ]
        include:
          - os: win
            runner: windows-2022
          - os: osx
            runner: macos-14
          - os: linux
            runner: ubuntu-20.04

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Prepare environment
        shell: pwsh
        run: |
          $Version = '${{ needs.preflight.outputs.version }}'
          Write-Host "Version: $Version"
          Set-Content -Path .\VERSION -Value $Version -NoNewLine -Force

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Windows runner
        if: matrix.os == 'win'
        shell: pwsh
        run: |
          choco install ninja 7zip wget
          Install-Module -Name VsDevShell -Force

      - name: Configure macOS runner
        if: matrix.os == 'osx'
        shell: pwsh
        run: |
          brew install ninja
          echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $Env:GITHUB_ENV

      - name: Configure Linux runner
        if: matrix.os == 'linux'
        shell: pwsh
        run: |
          sudo apt update
          sudo apt install xz-utils ninja-build

      - name: Install clang+llvm
        shell: pwsh
        run: |
          $ClangLlvmVersion='14.0.6'
          $ClangLlvmPlatform=@{'win'='windows';'osx'='macos';'linux'='ubuntu-20.04'}['${{matrix.os}}']
          $ClangLlvmBaseUrl="https://github.com/awakecoding/llvm-prebuilt/releases/download/v2023.1.0"
          $ClangLlvmName="clang+llvm-${ClangLlvmVersion}-x86_64-${ClangLlvmPlatform}"
          wget -q "${ClangLlvmBaseUrl}/${ClangLlvmName}.tar.xz"
          if ($IsWindows) {
            $LLVM_PREFIX="C:/llvm"
            cmd.exe /c "7z.exe x ${ClangLlvmName}.tar.xz -so | 7z x -si -ttar -o`"C:/temp`""
            mv "C:/temp/${ClangLlvmName}" $LLVM_PREFIX
          } else {
            $LLVM_PREFIX="/opt/llvm"
            tar -xf "${ClangLlvmName}.tar.xz" -C /tmp
            sudo mv "/tmp/${ClangLlvmName}" $LLVM_PREFIX
          }
          $LLVM_BIN_PATH="$LLVM_PREFIX/bin"
          $LLVM_DIR="$LLVM_PREFIX/lib/cmake/llvm"
          echo "LLVM_DIR=$LLVM_DIR" >> $Env:GITHUB_ENV
          echo "PATH=$LLVM_BIN_PATH$([IO.Path]::PathSeparator)$Env:PATH" >> $Env:GITHUB_ENV

      - name: Install Halide
        shell: pwsh
        run: |
          $HalideVersion='14.0.0'
          $HalidePlatform=@{'win'='windows';'osx'='macos';'linux'='ubuntu-20.04'}['${{matrix.os}}']
          $HalideBaseUrl="https://github.com/awakecoding/llvm-prebuilt/releases/download/v2023.1.0"
          $HalideName="halide-${HalideVersion}-x86_64-${HalidePlatform}"
          wget -q "${HalideBaseUrl}/${HalideName}.tar.xz"
          if ($IsWindows) {
            $HalidePrefix="C:/halide"
            cmd.exe /c "7z.exe x ${HalideName}.tar.xz -so | 7z x -si -ttar -o`"C:/temp`""
            mv "C:/temp/${HalideName}" $HalidePrefix
            mv $HalidePrefix/bin/*.dll $HalidePrefix/lib
          } else {
            $HalidePrefix="/opt/halide"
            tar -xf "${HalideName}.tar.xz" -C /tmp
            sudo mv "/tmp/${HalideName}" $HalidePrefix
          }
          echo "HALIDE_ROOT_DIR=$HalidePrefix" >> $Env:GITHUB_ENV

      - name: Configure CBake
        if: matrix.os == 'linux'
        shell: pwsh
        run: |
          $CBakeVersion = "v2023.11.08.0"
          $CBakeRepoUrl = "https://github.com/Devolutions/CBake"
          $CBakeDownloadUrl = "$CBakeRepoUrl/releases/download/$CBakeVersion"
          git clone -b $CBakeVersion "https://github.com/Devolutions/CBake" cbake
          @('ubuntu-20.04-amd64-sysroot.tar.xz', 'ubuntu-20.04-arm64-sysroot.tar.xz') | % {
            curl -L --output "cbake/sysroots/$_" "$CBakeDownloadUrl/$_"
            tar -C "cbake/sysroots" -xf "cbake/sysroots/$_"
            Remove-Item "cbake/sysroots/$_" | Out-Null
          }
          $CBakeHome = Join-Path (Get-Location) 'cbake'
          echo "CBAKE_HOME=$CBakeHome" >> $Env:GITHUB_ENV

      - name: Configure conan
        shell: pwsh
        run: |
          pip3 install conan==${{env.conan-version}} --upgrade
          conan config init
          conan config install --type=git -sf settings https://github.com/Devolutions/conan-public
          conan remote clean
          conan remote add artifactory https://devolutions.jfrog.io/devolutions/api/conan/conan-local

      - name: Build cadeau (${{matrix.os}}-${{matrix.arch}})
        shell: pwsh
        run: |
          $DotNetOs = '${{matrix.os}}'
          $DotNetArch = '${{matrix.arch}}'
          $DotNetRid = '${{matrix.os}}-${{matrix.arch}}'
          $BuildDir = "build-$DotNetRid"
          $NativeDir = ".\runtimes\${DotNetRid}\native"
          Remove-Item -Path $BuildDir -Recurse -ErrorAction SilentlyContinue | Out-Null
          New-Item -Path $BuildDir -ItemType Directory -ErrorAction SilentlyContinue | Out-Null
          New-Item -Path $NativeDir -ItemType Directory -ErrorAction SilentlyContinue | Out-Null

          $InstallPath = ".\install-${DotNetRid}"
          New-Item -Path $InstallPath -ItemType Directory -ErrorAction SilentlyContinue | Out-Null
          
          $CMakeArgs = @("-DCMAKE_BUILD_TYPE=Release")
          $CMakeArgs += @("-DCMAKE_INSTALL_PREFIX=$InstallPath")
          $CMakeArgs += @("-DHALIDE_ROOT_DIR=$($Env:HALIDE_ROOT_DIR)")
          $CMakeArgs += @("-DWITH_XMF=ON", "-DUSE_CONAN=ON")

          if ($DotNetOs -eq 'win') {
            $MsvcArch = @{'x64'='x64';'arm64'='ARM64'}[$DotNetArch]
            Enter-VsDevShell $MsvcArch
            cmake -G Ninja . -B $BuildDir $CMakeArgs
            cmake --build $BuildDir --config Release
            cmake --install $BuildDir --config Release
            Copy-Item "$BuildDir\lib\xmf.dll" "$NativeDir\xmf.dll" -Force
          }
          elseif ($DotNetOs -eq 'osx') {
            $AppleArch = @{'x64'='x86_64';'arm64'='arm64'}[$DotNetArch]
            $CMakeArgs += "-DCMAKE_OSX_ARCHITECTURES=$AppleArch"
            cmake . -G Ninja -B $BuildDir $CMakeArgs
            cmake --build $BuildDir
            cmake --install $BuildDir
            Copy-Item "$BuildDir\lib\libxmf.dylib" "$NativeDir\libxmf.dylib" -Force
          }
          elseif ($DotNetOs -eq 'linux') {
            $LinuxArch = @{'x64'='amd64';'arm64'='arm64'}[$DotNetArch]
            $CMakeToolchainFile = Join-Path $Env:CBAKE_HOME "cmake/linux.toolchain.cmake"
            $CMakeArgs += "-DSYSROOT_NAME=ubuntu-20.04-$LinuxArch"
            $CMakeArgs += "-DCMAKE_TOOLCHAIN_FILE=$CMakeToolchainFile"
            cmake . -G Ninja -B $BuildDir $CMakeArgs
            cmake --build $BuildDir
            cmake --install $BuildDir
            Copy-Item "$BuildDir\lib\libxmf.so" "$NativeDir\libxmf.so" -Force
          }

      - name: Upload native components (${{matrix.os}}-${{matrix.arch}})
        uses: actions/upload-artifact@v4
        with:
          name: runtimes-${{matrix.os}}-${{matrix.arch}}
          path: runtimes

  build-universal:
    name: Universal Build
    runs-on: ubuntu-20.04
    needs: [preflight, build-native]

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Configure runner
        run: |
          wget -q https://github.com/awakecoding/llvm-prebuilt/releases/download/v2023.3.0/cctools-x86_64-ubuntu-20.04.tar.xz
          tar -xf cctools-x86_64-ubuntu-20.04.tar.xz -C /tmp
          sudo mv /tmp/cctools-x86_64-ubuntu-20.04/bin/lipo /usr/local/bin
          sudo mv /tmp/cctools-x86_64-ubuntu-20.04/bin/install_name_tool /usr/local/bin

      - name: Download native components
        uses: actions/download-artifact@v4
        with:
          pattern: runtimes-*-*
          merge-multiple: true
          path: runtimes

      - name: merge thin libraries
        shell: pwsh
        run: |
          $LibraryName = "libxmf"
          $OutputPath = "./runtimes/osx-universal/native"
          New-Item -ItemType Directory -Path $OutputPath -ErrorAction SilentlyContinue | Out-Null
          $ThinLibraries = Get-ChildItem "./runtimes/osx-*/native/$LibraryName.dylib" -Exclude "*-universal*" | Select-Object -ExpandProperty FullName
          & 'lipo' '-create' @ThinLibraries '-output' "$OutputPath/$LibraryName.dylib"

      - name: Upload native components
        uses: actions/upload-artifact@v4
        with:
          name: runtimes-all
          path: runtimes

  build-managed:
    name: Managed build
    runs-on: windows-2022
    needs: [preflight, build-native, build-universal]

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Download native components
        uses: actions/download-artifact@v4
        with:
          name: runtimes-all
          path: runtimes

      - name: Build nuget package
        shell: pwsh
        run: |
          $Version = '${{ needs.preflight.outputs.version }}'
          & dotnet pack .\dotnet\Devolutions.Cadeau -o package /p:Version=$Version

      - name: Upload managed components
        uses: actions/upload-artifact@v4
        with:
          name: cadeau-nupkg
          path: package/*.nupkg
